-- Esquema inicial do Baixo K. -- versao Postgres (Supabase).
--
-- Traducao 1:1 de ../001_esquema_inicial.sql, que e SQLite. As diferencas de
-- dialeto estao anotadas onde aparecem; o resto e identico de proposito, para
-- os dois bancos continuarem comparaveis linha a linha.
--
-- Rodar no SQL Editor do Supabase na ordem 001 -> 002 -> 003 -> 004. O editor
-- executa tudo numa transacao: se um comando falhar, nada e criado e da para
-- corrigir e colar de novo sem limpar nada antes.

-- citext = TEXT que compara ignorando maiusculas, o equivalente do
-- `COLLATE NOCASE` do SQLite. Precisa ser um tipo de verdade (e nao um indice
-- sobre lower(...)) porque `cupons.code` e chave primaria referenciada por
-- cupons_resgatados, e chave estrangeira exige unicidade na propria coluna.
-- O Supabase ja cria o schema `extensions`; um PostgreSQL padrao (como o da
-- Square Cloud) nao. Criar se ausente mantem a migration portavel nos dois.
-- O tipo fica qualificado no DDL para rodar mesmo com search_path apertado.
CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA extensions;

-- ---------------------------------------------------------------- pessoas ---
-- AUTOINCREMENT nao existe no Postgres: o equivalente e IDENTITY. BY DEFAULT
-- (em vez de ALWAYS) mantem o import do legado podendo gravar o id explicito.
CREATE TABLE usuarios (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario       extensions.CITEXT NOT NULL UNIQUE,
  nome          TEXT        NOT NULL,
  senha_hash    TEXT        NOT NULL,
  papel         TEXT        NOT NULL CHECK (papel IN ('admin', 'caixa', 'cozinha', 'entregador')),
  ativo         INTEGER     NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
  criado_em     TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  ultimo_login  TIMESTAMPTZ
);

-- Guardamos o hash do token, nunca o token. Um vazamento do arquivo do banco
-- (backup em pendrive, copia por e-mail) deixava de entregar sessao viva.
CREATE TABLE sessoes (
  token_hash  TEXT        PRIMARY KEY,
  usuario_id  BIGINT      NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  csrf_hash   TEXT        NOT NULL,
  criada_em   TIMESTAMPTZ NOT NULL DEFAULT now(),
  expira_em   TIMESTAMPTZ NOT NULL,
  ip          TEXT,
  agente      TEXT
);
CREATE INDEX idx_sessoes_usuario ON sessoes(usuario_id);
CREATE INDEX idx_sessoes_expira  ON sessoes(expira_em);

-- Responde "quem cancelou aquele pedido de ontem?", que com a senha unica
-- compartilhada nao tinha resposta possivel.
CREATE TABLE auditoria (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id  BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
  usuario     TEXT,
  acao        TEXT NOT NULL,
  entidade    TEXT,
  entidade_id TEXT,
  detalhes    TEXT,
  ip          TEXT,
  criado_em   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_auditoria_criado ON auditoria(criado_em);
CREATE INDEX idx_auditoria_entidade ON auditoria(entidade, entidade_id);

-- --------------------------------------------------------------- cardapio ---
-- REAL do SQLite e float de 8 bytes; o REAL do Postgres so tem 4 e perde
-- centavo em valor alto, entao dinheiro vira DOUBLE PRECISION. Trocar por
-- NUMERIC(10,2) e mais correto para moeda, mas o supabase-js devolve NUMERIC
-- como string e a conta de subtotal no app quebraria calada.
CREATE TABLE produtos (
  id            TEXT             PRIMARY KEY,
  nome          TEXT             NOT NULL,
  categoria     TEXT             NOT NULL,
  preco         DOUBLE PRECISION NOT NULL CHECK (preco >= 0),
  estoque       INTEGER          NOT NULL DEFAULT 0 CHECK (estoque >= 0),
  estoque_min   INTEGER          NOT NULL DEFAULT 4 CHECK (estoque_min >= 0),
  ordem         INTEGER          NOT NULL DEFAULT 9999 CHECK (ordem > 0),
  ativo         INTEGER          NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
  imagem        TEXT             NOT NULL DEFAULT '',
  selo          TEXT             NOT NULL DEFAULT '',
  descricao     TEXT             NOT NULL DEFAULT '',
  criado_em     TIMESTAMPTZ      NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ      NOT NULL DEFAULT now()
);
CREATE INDEX idx_produtos_categoria ON produtos(categoria, ativo);
CREATE INDEX idx_produtos_ordem ON produtos(ordem, categoria, nome);

-- UNIQUE em produto_id: a regra "uma promocao por produto" era mantida na mao
-- pelo front (filter + unshift) e nada impedia duas promocoes no mesmo item se
-- duas abas salvassem juntas. Agora e o banco que recusa.
CREATE TABLE promocoes (
  id         TEXT             PRIMARY KEY,
  produto_id TEXT             NOT NULL UNIQUE REFERENCES produtos(id) ON DELETE CASCADE,
  preco      DOUBLE PRECISION NOT NULL CHECK (preco >= 0),
  ate        TEXT             NOT NULL DEFAULT '',
  criado_em  TIMESTAMPTZ      NOT NULL DEFAULT now()
);

-- `ate` continua TEXT nos dois bancos: string vazia e o sentinela de "sem
-- validade", e uma coluna DATE nao aceitaria ''.
CREATE TABLE cupons (
  code      extensions.CITEXT PRIMARY KEY,
  tipo      TEXT              NOT NULL CHECK (tipo IN ('pct', 'val')),
  valor     DOUBLE PRECISION  NOT NULL CHECK (valor > 0),
  minimo    DOUBLE PRECISION  NOT NULL DEFAULT 0 CHECK (minimo >= 0),
  uso_unico INTEGER           NOT NULL DEFAULT 0 CHECK (uso_unico IN (0, 1)),
  ate       TEXT              NOT NULL DEFAULT '',
  usos      INTEGER           NOT NULL DEFAULT 0 CHECK (usos >= 0),
  ativo     INTEGER           NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
  criado_em TIMESTAMPTZ       NOT NULL DEFAULT now()
);

-- Tabela que faltava. O README listava "cupom de uso unico nao e aplicado" como
-- limitacao conhecida: o sistema guardava a marca e nunca a checava. Com o
-- telefone do pedido da para fechar a regra.
CREATE TABLE cupons_resgatados (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cupom_code extensions.CITEXT NOT NULL REFERENCES cupons(code) ON DELETE CASCADE,
  pedido_id  TEXT              NOT NULL,
  telefone   TEXT              NOT NULL DEFAULT '',
  criado_em  TIMESTAMPTZ       NOT NULL DEFAULT now()
);
CREATE INDEX idx_resgate_cupom_tel ON cupons_resgatados(cupom_code, telefone);

-- ------------------------------------------------------------------ salao ---
-- Criada antes de `pedidos` porque pedidos referencia mesas(n).
CREATE TABLE mesas (
  n             INTEGER     PRIMARY KEY,
  status        TEXT        NOT NULL DEFAULT 'livre' CHECK (status IN ('livre', 'aberta', 'fechando')),
  aberta_em     TIMESTAMPTZ,
  fechada_em    TIMESTAMPTZ,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------- pedidos ---
-- `local` e palavra-chave nao reservada no Postgres, entao passa sem aspas.
CREATE TABLE pedidos (
  id              TEXT             PRIMARY KEY,
  criado_em       TIMESTAMPTZ      NOT NULL DEFAULT now(),
  status          TEXT             NOT NULL DEFAULT 'novo' CHECK (status IN ('novo', 'preparo', 'pronto', 'entregue', 'cancelado')),
  canal           TEXT             NOT NULL DEFAULT 'cardapio',
  modalidade      TEXT             NOT NULL DEFAULT 'retirada' CHECK (modalidade IN ('retirada', 'entrega', 'mesa')),
  cliente         TEXT             NOT NULL DEFAULT 'Cliente',
  telefone        TEXT             NOT NULL DEFAULT '',
  local           TEXT             NOT NULL DEFAULT '',
  observacao      TEXT             NOT NULL DEFAULT '',
  motivo_cancelamento TEXT         NOT NULL DEFAULT '',
  pagamento       TEXT             NOT NULL DEFAULT '',
  mesa_n          INTEGER          REFERENCES mesas(n) ON DELETE SET NULL,
  subtotal        DOUBLE PRECISION NOT NULL DEFAULT 0,
  desconto        DOUBLE PRECISION NOT NULL DEFAULT 0,
  cupom_code      TEXT             NOT NULL DEFAULT '',
  taxa_entrega    DOUBLE PRECISION NOT NULL DEFAULT 0,
  entrega_km      DOUBLE PRECISION,
  entrega_faixa   TEXT,
  total           DOUBLE PRECISION NOT NULL DEFAULT 0,
  motoboy         TEXT             NOT NULL DEFAULT '',
  impresso        INTEGER          NOT NULL DEFAULT 0 CHECK (impresso IN (0, 1)),
  estoque_baixado INTEGER          NOT NULL DEFAULT 0 CHECK (estoque_baixado IN (0, 1)),
  criado_por      BIGINT           REFERENCES usuarios(id) ON DELETE SET NULL,
  atualizado_em   TIMESTAMPTZ      NOT NULL DEFAULT now()
);
CREATE INDEX idx_pedidos_criado ON pedidos(criado_em DESC);
CREATE INDEX idx_pedidos_status ON pedidos(status, criado_em DESC);
CREATE INDEX idx_pedidos_mesa   ON pedidos(mesa_n);

-- Item vira linha. Antes era um array JSON dentro do pedido, o que impedia
-- somar "mais vendidos" sem carregar e percorrer todos os pedidos do periodo.
CREATE TABLE pedido_itens (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id   TEXT             NOT NULL REFERENCES pedidos(id) ON DELETE CASCADE,
  produto_id  TEXT             REFERENCES produtos(id) ON DELETE SET NULL,
  nome        TEXT             NOT NULL,
  quantidade  INTEGER          NOT NULL CHECK (quantidade > 0),
  preco_unit  DOUBLE PRECISION NOT NULL CHECK (preco_unit >= 0)
);
CREATE INDEX idx_itens_pedido  ON pedido_itens(pedido_id);
CREATE INDEX idx_itens_produto ON pedido_itens(produto_id);

CREATE TABLE insumos (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome          TEXT             NOT NULL,
  categoria     TEXT             NOT NULL DEFAULT 'Geral',
  unidade       TEXT             NOT NULL DEFAULT 'un',
  quantidade    DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (quantidade >= 0),
  minimo        DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (minimo >= 0),
  ativo         INTEGER          NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
  criado_em     TIMESTAMPTZ      NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ      NOT NULL DEFAULT now()
);
CREATE INDEX idx_insumos_categoria ON insumos(categoria, ativo);
CREATE INDEX idx_insumos_minimo ON insumos(quantidade, minimo);

CREATE TABLE mesa_itens (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mesa_n     INTEGER          NOT NULL REFERENCES mesas(n) ON DELETE CASCADE,
  pedido_id  TEXT             REFERENCES pedidos(id) ON DELETE CASCADE,
  produto_id TEXT             REFERENCES produtos(id) ON DELETE SET NULL,
  nome       TEXT             NOT NULL,
  quantidade INTEGER          NOT NULL CHECK (quantidade > 0),
  preco_unit DOUBLE PRECISION NOT NULL CHECK (preco_unit >= 0),
  criado_em  TIMESTAMPTZ      NOT NULL DEFAULT now()
);
CREATE INDEX idx_mesa_itens ON mesa_itens(mesa_n);

-- ---------------------------------------------------------------- entrega ---
-- Linha unica travada em id = 1.
CREATE TABLE entrega_config (
  id            INTEGER          PRIMARY KEY CHECK (id = 1),
  endereco      TEXT             NOT NULL DEFAULT '',
  lng           DOUBLE PRECISION,
  lat           DOUBLE PRECISION,
  atualizado_em TIMESTAMPTZ      NOT NULL DEFAULT now()
);
INSERT INTO entrega_config (id, endereco) VALUES (1, '') ON CONFLICT (id) DO NOTHING;

CREATE TABLE entrega_faixas (
  id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  km     DOUBLE PRECISION NOT NULL CHECK (km > 0),
  taxa   DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (taxa >= 0),
  minimo DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (minimo >= 0)
);

-- ------------------------------------------------------- ajustes da casa ---
-- Coisas que estavam cravadas no app.js e por isso so mudavam com deploy:
-- MENU_URL, DELIVERY_WHATSAPP e a taxa de servico de 10%.
CREATE TABLE ajustes (
  chave TEXT PRIMARY KEY,
  valor TEXT NOT NULL
);

-- -------------------------------------------------------------------- RLS ---
-- Sem isto o Supabase publica cada tabela na API REST automatica, e a chave
-- anon do cardapio le `usuarios.senha_hash` e `sessoes.token_hash` direto do
-- navegador do cliente. Ligar RLS sem nenhuma policy fecha tudo: so a
-- service_role (que ignora RLS) enxerga, que e exatamente o backend.
-- Quando o front for falar direto com o Supabase, criar policy por tabela.
ALTER TABLE usuarios          ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessoes           ENABLE ROW LEVEL SECURITY;
ALTER TABLE auditoria         ENABLE ROW LEVEL SECURITY;
ALTER TABLE produtos          ENABLE ROW LEVEL SECURITY;
ALTER TABLE promocoes         ENABLE ROW LEVEL SECURITY;
ALTER TABLE cupons            ENABLE ROW LEVEL SECURITY;
ALTER TABLE cupons_resgatados ENABLE ROW LEVEL SECURITY;
ALTER TABLE mesas             ENABLE ROW LEVEL SECURITY;
ALTER TABLE pedidos           ENABLE ROW LEVEL SECURITY;
ALTER TABLE pedido_itens      ENABLE ROW LEVEL SECURITY;
ALTER TABLE insumos           ENABLE ROW LEVEL SECURITY;
ALTER TABLE mesa_itens        ENABLE ROW LEVEL SECURITY;
ALTER TABLE entrega_config    ENABLE ROW LEVEL SECURITY;
ALTER TABLE entrega_faixas    ENABLE ROW LEVEL SECURITY;
ALTER TABLE ajustes           ENABLE ROW LEVEL SECURITY;
