-- Insumos operacionais e motoboy responsavel por entrega.

CREATE TABLE IF NOT EXISTS insumos (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome          TEXT        NOT NULL,
  categoria     TEXT        NOT NULL DEFAULT 'Geral',
  unidade       TEXT        NOT NULL DEFAULT 'un',
  quantidade    DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (quantidade >= 0),
  minimo        DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (minimo >= 0),
  ativo         INTEGER     NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
  criado_em     TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_insumos_categoria ON insumos(categoria, ativo);
CREATE INDEX IF NOT EXISTS idx_insumos_minimo ON insumos(quantidade, minimo);

ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS motoboy TEXT NOT NULL DEFAULT '';

ALTER TABLE insumos ENABLE ROW LEVEL SECURITY;
