-- Historico de fechamento de conta de mesa: registra se a taxa de servico (a
-- "taxa do garcom") foi cobrada ou nao em cada comanda fechada. A mesa em si
-- (tabela `mesas`) e reaproveitada a cada cliente, entao nao guarda historico
-- -- este e o ledger que o dashboard consulta para somar arrecadacao de servico
-- e contar quantas contas fecharam sem cobrar.
CREATE TABLE mesas_fechamentos (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mesa_n          INTEGER          NOT NULL,
  subtotal        DOUBLE PRECISION NOT NULL DEFAULT 0,
  percentual      DOUBLE PRECISION NOT NULL DEFAULT 0,
  servico         DOUBLE PRECISION NOT NULL DEFAULT 0,
  servico_cobrado INTEGER          NOT NULL DEFAULT 1 CHECK (servico_cobrado IN (0, 1)),
  total           DOUBLE PRECISION NOT NULL DEFAULT 0,
  usuario         TEXT,
  criado_em       TIMESTAMPTZ      NOT NULL DEFAULT now()
);
CREATE INDEX idx_mesas_fechamentos_criado ON mesas_fechamentos(criado_em DESC);
