-- Pizza de 2 sabores e combos.
--
-- Sabor de pizza continua sendo um produto normal do cardapio (mesma foto,
-- mesmo preco de "1 sabor"). `sabor_pizza` so marca quais produtos entram na
-- tela de "quantos sabores?" no cardapio do cliente.
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS sabor_pizza INTEGER NOT NULL DEFAULT 0 CHECK (sabor_pizza IN (0, 1));

-- Preco de cada combinacao de 2 sabores e sempre configurado pelo lojista —
-- nao existe regra automatica (media, maior valor...). Sem uma linha aqui, a
-- combinacao simplesmente nao aparece como opcao pro cliente. Par normalizado
-- (produto_a_id < produto_b_id) pra nao guardar A+B e B+A como coisas
-- diferentes.
CREATE TABLE combinacoes_sabores (
  produto_a_id  TEXT             NOT NULL REFERENCES produtos(id) ON DELETE CASCADE,
  produto_b_id  TEXT             NOT NULL REFERENCES produtos(id) ON DELETE CASCADE,
  preco         DOUBLE PRECISION NOT NULL,
  criado_em     TIMESTAMPTZ      NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ      NOT NULL DEFAULT now(),
  PRIMARY KEY (produto_a_id, produto_b_id),
  CHECK (produto_a_id < produto_b_id)
);

-- Combo e um item vendavel proprio (nome, foto, preco fechado), composto por
-- produtos existentes. Estrutura espelha `produtos` no essencial; estoque
-- continua vivendo em cada produto componente, nao aqui.
CREATE TABLE combos (
  id            TEXT             PRIMARY KEY,
  nome          TEXT             NOT NULL,
  descricao     TEXT             NOT NULL DEFAULT '',
  preco         DOUBLE PRECISION NOT NULL,
  imagem        TEXT             NOT NULL DEFAULT '',
  ativo         INTEGER          NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
  ordem         INTEGER          NOT NULL DEFAULT 9999,
  criado_em     TIMESTAMPTZ      NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ      NOT NULL DEFAULT now()
);

-- RESTRICT (nao CASCADE): apagar um produto que faz parte de um combo ativo
-- quebraria a venda do combo sem avisar ninguem. O cadastro tem que tirar do
-- combo primeiro.
CREATE TABLE combo_itens (
  id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  combo_id    TEXT    NOT NULL REFERENCES combos(id) ON DELETE CASCADE,
  produto_id  TEXT    NOT NULL REFERENCES produtos(id) ON DELETE RESTRICT,
  quantidade  INTEGER NOT NULL DEFAULT 1 CHECK (quantidade > 0)
);
CREATE INDEX idx_combo_itens_combo ON combo_itens(combo_id);

-- Pedido carrega a referencia do que foi vendido como combo (combo_id) ou
-- como pizza de 2 sabores (produto_id ja existe = 1o sabor; produto_id_2 = 2o
-- sabor). Nos dois casos o preco fechado fica em `preco_unit`, igual a
-- qualquer outra linha.
ALTER TABLE pedido_itens ADD COLUMN combo_id TEXT REFERENCES combos(id) ON DELETE SET NULL;
ALTER TABLE pedido_itens ADD COLUMN produto_id_2 TEXT REFERENCES produtos(id) ON DELETE SET NULL;
