-- Escolhas dentro de um combo (ex: "Escolha o refrigerante": Coca-Cola +R$2,
-- Guarana, Coca Zero, Fanta Uva, Fanta Laranja). Diferente de combo_itens
-- (produto fixo do combo), aqui o cliente escolhe UMA opcao entre varias na
-- hora de montar o pedido, e cada opcao pode ter um acrescimo de preco.
CREATE TABLE combo_escolhas (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  combo_id TEXT    NOT NULL REFERENCES combos(id) ON DELETE CASCADE,
  nome     TEXT    NOT NULL,
  ordem    INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX idx_combo_escolhas_combo ON combo_escolhas(combo_id);

-- RESTRICT: mesma regra do combo_itens — apagar um produto que e opcao de
-- escolha ativa quebraria o combo sem avisar.
CREATE TABLE combo_escolha_opcoes (
  id          BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escolha_id  BIGINT           NOT NULL REFERENCES combo_escolhas(id) ON DELETE CASCADE,
  produto_id  TEXT             NOT NULL REFERENCES produtos(id) ON DELETE RESTRICT,
  preco_extra DOUBLE PRECISION NOT NULL DEFAULT 0
);
CREATE INDEX idx_combo_escolha_opcoes_escolha ON combo_escolha_opcoes(escolha_id);

-- O que o cliente escolheu fica gravado no proprio pedido — nao da pra
-- recalcular depois olhando o cadastro do combo, porque a escolha e de cada
-- cliente, nao do combo. JSON simples, no mesmo espirito do `detalhes` da
-- auditoria: `[{"produtoId":"...","produtoNome":"...","precoExtra":2}]`.
ALTER TABLE pedido_itens ADD COLUMN escolhas TEXT NOT NULL DEFAULT '[]';
