-- Numero sequencial do pedido. Diferente do `id` (texto aleatorio, usado como
-- chave e em URL — nunca deveria virar a "senha" que o cliente grita no
-- balcao), este e um inteiro que so cresce: 1, 2, 3... Nunca repete porque
-- vem de uma sequence do proprio Postgres, e continua avancando mesmo que um
-- pedido seja cancelado ou apagado depois — o numero de um pedido excluido
-- nunca volta a ser usado por outro.
--
-- Adicionar como IDENTITY numa tabela que ja tem linhas preenche os pedidos
-- existentes tambem, na hora do ALTER — ninguem fica sem numero.
ALTER TABLE pedidos ADD COLUMN numero BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE;

CREATE INDEX idx_pedidos_numero ON pedidos(numero);
